import { ColumnType, Insertable, Selectable, Updateable } from 'kysely';

// ── tenants ──────────────────────────────────────────────────────────────────
export interface TenantsTable {
  id: string;                              // TEXT PRIMARY KEY (UUID)
  name: string;                            // TEXT NOT NULL
  created_at: ColumnType<Date, string, never>;
}

// ── users ────────────────────────────────────────────────────────────────────
export interface UsersTable {
  id: string;                              // TEXT PRIMARY KEY (UUID)
  tenant_id: string;                       // TEXT NOT NULL REFERENCES tenants(id)
  email: string;                           // TEXT NOT NULL
  password_hash: string;                   // TEXT NOT NULL
  role: 'admin' | 'user';                 // TEXT NOT NULL DEFAULT 'user'
  created_at: ColumnType<Date, string, never>;
  updated_at: ColumnType<Date, string, string>;
}

// ── notes ────────────────────────────────────────────────────────────────────
export interface NotesTable {
  id: string;                              // TEXT PRIMARY KEY (UUID)
  tenant_id: string;                       // TEXT NOT NULL REFERENCES tenants(id)
  author_id: string;                       // TEXT NOT NULL REFERENCES users(id)
  title: string;                           // TEXT NOT NULL
  content: string;                         // TEXT NOT NULL
  created_at: ColumnType<Date, string, never>;
  updated_at: ColumnType<Date, string, string>;
}

// ── meetings ─────────────────────────────────────────────────────────────────
export interface MeetingsTable {
  id: string;                              // TEXT PRIMARY KEY (UUID)
  tenant_id: string;                       // TEXT NOT NULL REFERENCES tenants(id)
  organizer_id: string;                    // TEXT NOT NULL REFERENCES users(id)
  title: string;                           // TEXT NOT NULL
  description: string;                     // TEXT NOT NULL
  start_at: ColumnType<Date, string, string>;  // TEXT NOT NULL (ISO-8601)
  end_at: ColumnType<Date, string, string>;    // TEXT NOT NULL (ISO-8601)
  location: string | null;                 // TEXT NULLABLE
  created_at: ColumnType<Date, string, never>;
  updated_at: ColumnType<Date, string, string>;
}

// ── root DB map ───────────────────────────────────────────────────────────────
export interface Database {
  tenants: TenantsTable;
  users: UsersTable;
  notes: NotesTable;
  meetings: MeetingsTable;
}

// Convenience row types generated by Kysely helpers
export type TenantRow     = Selectable<TenantsTable>;
export type NewTenant     = Insertable<TenantsTable>;

export type UserRow       = Selectable<UsersTable>;
export type NewUser       = Insertable<UsersTable>;
export type UpdateUser    = Updateable<UsersTable>;

export type NoteRow       = Selectable<NotesTable>;
export type NewNote       = Insertable<NotesTable>;
export type UpdateNote    = Updateable<NotesTable>;

export type MeetingRow    = Selectable<MeetingsTable>;
export type NewMeeting    = Insertable<MeetingsTable>;
export type UpdateMeeting = Updateable<MeetingsTable>;
